Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> As part of this cleanup, can you also check the properties files under sdnc-a1-controller/oam/installation/src/main/properties/?
> 
> Are we using this sdnctl.dump?

Our A1 adapter still works fine after removing sdnctl.dump as we are not using it at all. But the logs show some exceptions due to this:

0.6.3 |  -  | <sdnctldb01> Failed to execute: SELECT count(*) FROM SVC_LOGIC WHERE module = ? AND rpc = ? AND mode = ? AND active = 'Y' with arguments: [sli, healthcheck, sync]
java.sql.SQLSyntaxErrorException: (conn=14) Table 'sdnctl.SVC_LOGIC' doesn't exist

I will try to investigate if we can completely remove this database from our controller although it seems like it is tightly integrated with SDNC. I will raise a new review if I succeed in doing this. In the meanwhile, I think this commit can be merged.

Patch-set: 5