Print the short description of exception in OscA1Client
Avoid garbage from running the unit-tests which cause exceptions.
Now, it prints just one line:
ERROR org.oransc.policyagent.clients.OscA1Client - Unexpected response for policy type: {"type":"type1"},
exception: org.json.JSONException: JSONObject["create_schema"] not found.

Change-Id: I6c5d0037b9d068a1fd069d521af1070a8ec55c54
Signed-off-by: RehanRaza <muhammad.rehan.raza@est.tech>